org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

# 优化 Gradle 构建
org.gradle.parallel=true
#org.gradle.caching=true
org.gradle.configureondemand=true

# AndroidX
android.enableJetifier=false

# Fix kapt incompatibility with Kotlin 2.x
kapt.use.worker.api=false
kapt.include.compile.classpath=false